import type { RuntimeConfig } from "../config/runtime.js";
import { analyzeEvidence, type AnalysisResult } from "../analysis/analyzer.js";
import { loadAnalysisConfig } from "../analysis/config-loader.js";
import type { TokenProvider } from "../auth/token-provider.js";
import { digestCanonical, newRunId, stableRecordKey } from "../domain/identity.js";
import { LIST_MANIFESTS, type ColumnDefinition } from "../domain/list-manifests.js";
import type { ApplyResult, DerivedRecord } from "../domain/models.js";
import { collectEvidence } from "../extraction/extractor.js";
import { GraphClient } from "../graph/client.js";
import {
  SharePointDestinationWriter,
  type DestinationWriter,
} from "../graph/destination-adapter.js";
import {
  SharePointSchemaManager,
  type SchemaManager,
  type SchemaOperation,
} from "../graph/schema-manager.js";
import { SharePointSourceReader } from "../graph/source-adapter.js";
import { resolveSite, resolveSourceFolder } from "../graph/url-resolver.js";
import { PlanStore } from "../planning/plan-store.js";
import { applyUpserts, planUpserts } from "../planning/upsert-planner.js";

export interface AnalysisSession extends AnalysisResult {
  runId: string;
  sourceCount: number;
}

export interface ServiceDependencies {
  tokenProvider: TokenProvider;
  graphClient?: GraphClient;
  planStore?: PlanStore;
  destinationFactory?: (siteId: string) => DestinationWriter;
  schemaManagerFactory?: (siteId: string) => SchemaManager;
}

export class UiEvidenceService {
  readonly #client: GraphClient;
  readonly #plans: PlanStore;
  readonly #analyses = new Map<string, AnalysisSession>();

  constructor(
    private readonly config: RuntimeConfig,
    private readonly dependencies: ServiceDependencies,
  ) {
    this.#client = dependencies.graphClient ?? new GraphClient(dependencies.tokenProvider);
    this.#plans = dependencies.planStore ?? new PlanStore();
  }

  async analyzeSource(): Promise<AnalysisSession> {
    const [root, analysisConfig] = await Promise.all([
      resolveSourceFolder(this.#client, this.config.sourceFolderUrl),
      loadAnalysisConfig(),
    ]);
    const source = new SharePointSourceReader(this.#client, root);
    const evidence = await collectEvidence(source, this.config);
    const runId = newRunId();
    const sourceScopeKey = digestCanonical({
      sourceDriveId: root.driveId,
      sourceItemId: root.itemId,
    });
    const result = analyzeEvidence(
      evidence,
      runId,
      sourceScopeKey,
      analysisConfig.taxonomy,
      analysisConfig.riskRules,
      this.config.storeExcerpts,
    );
    const runRecord: DerivedRecord = {
      sourceDriveId: root.driveId,
      sourceItemId: root.itemId,
      sourceLink: root.webUrl,
      sourceScopeKey,
      key: stableRecordKey(
        {
          sourceDriveId: root.driveId,
          sourceItemId: root.itemId,
          sourceLink: root.webUrl,
        },
        "analysis-run",
        runId,
      ),
      kind: "analysis-run",
      title: `UI evidence analysis ${runId}`,
      sourceStatus: "available",
      analysisRunId: runId,
      classification: "analysis-run",
      confidence: 1,
      reviewRequired: result.failures.length > 0,
      conflicts: [],
      provenance: {
        assertionKind: "documented-fact",
        rationale: "Operational record generated by the analysis service.",
      },
      details: {
        sourceCount: evidence.length,
        derivedRecordCount: result.records.length,
        failureCount: result.failures.length,
        failures: result.failures,
      },
      rulesVersion: `${analysisConfig.taxonomy.version}/${analysisConfig.riskRules.version}`,
    };
    const session: AnalysisSession = {
      runId,
      sourceCount: evidence.length,
      records: [...result.records, runRecord],
      failures: result.failures,
    };
    this.#analyses.set(runId, session);
    return session;
  }

  async previewSchema() {
    const site = await resolveSite(this.#client, this.config.destinationSiteUrl);
    const operations = await this.schemaManager(site.id).preview(LIST_MANIFESTS);
    return this.#plans.create({
      kind: "schema",
      destinationSiteId: site.id,
      ttlMinutes: this.config.planTtlMinutes,
      schemaOperations: operations,
    });
  }

  async previewUpsert(runId: string) {
    const analysis = this.#analyses.get(runId);
    if (!analysis) throw new Error(`Unknown analysis run: ${runId}`);
    const site = await resolveSite(this.#client, this.config.destinationSiteUrl);
    const destination = this.destination(site.id);
    const scopeKey = analysis.records[0]?.sourceScopeKey;
    if (!scopeKey) throw new Error(`Analysis run ${runId} contains no source scope`);
    const unavailable = buildUnavailableRecords(
      analysis,
      await destination.listByScope("UI Evidence Index", scopeKey),
    );
    const changes = await planUpserts([...analysis.records, ...unavailable], destination);
    return this.#plans.create({
      kind: "upsert",
      destinationSiteId: site.id,
      ttlMinutes: this.config.planTtlMinutes,
      changes,
    });
  }

  async approvePlan(planId: string, digest: string, confirmation: string) {
    const accessToken = await this.dependencies.tokenProvider.getAccessToken();
    return this.#plans.approve(planId, digest, accessToken.accountId, confirmation);
  }

  async applySchema(planId: string) {
    const accessToken = await this.dependencies.tokenProvider.getAccessToken();
    const { plan, approval } = this.#plans.consumeApproval(planId, "schema", accessToken.accountId);
    const site = await resolveSite(this.#client, this.config.destinationSiteUrl);
    assertDestination(plan.destinationSiteId, site.id);
    const operations = plan.schemaOperations.map(parseSchemaOperation);
    const outcomes = await this.schemaManager(site.id).apply(operations);
    const failures = outcomes.filter((outcome) => outcome.status === "failed").length;
    return {
      planId,
      approvedBy: approval.approvedBy,
      status:
        failures === 0
          ? ("succeeded" as const)
          : failures === outcomes.length
            ? ("failed" as const)
            : ("partially-succeeded" as const),
      outcomes,
    };
  }

  async applyUpsert(planId: string): Promise<ApplyResult & { approvedBy: string }> {
    const accessToken = await this.dependencies.tokenProvider.getAccessToken();
    const { plan, approval } = this.#plans.consumeApproval(planId, "upsert", accessToken.accountId);
    const site = await resolveSite(this.#client, this.config.destinationSiteUrl);
    assertDestination(plan.destinationSiteId, site.id);
    const result = await applyUpserts(planId, plan.changes, this.destination(site.id));
    return { ...result, approvedBy: approval.approvedBy };
  }

  private destination(siteId: string): DestinationWriter {
    return (
      this.dependencies.destinationFactory?.(siteId) ??
      new SharePointDestinationWriter(this.#client, siteId)
    );
  }

  private schemaManager(siteId: string): SchemaManager {
    return (
      this.dependencies.schemaManagerFactory?.(siteId) ??
      new SharePointSchemaManager(this.#client, siteId)
    );
  }
}

function buildUnavailableRecords(
  analysis: AnalysisSession,
  destinationRecords: Awaited<ReturnType<DestinationWriter["listByScope"]>>,
): DerivedRecord[] {
  const currentKeys = new Set(
    analysis.records
      .filter((record) => record.kind === "evidence-index")
      .map((record) => record.key),
  );
  const template = analysis.records[0];
  if (!template) return [];

  return destinationRecords
    .filter((destination) => {
      const key = stringField(destination.fields, "StableKey");
      return key !== undefined && !currentKeys.has(key);
    })
    .map((destination) => {
      const fields = destination.fields;
      const key = requiredStringField(fields, "StableKey");
      const contentHash = stringField(fields, "ContentHash");
      return {
        key,
        kind: "evidence-index" as const,
        title: requiredStringField(fields, "Title"),
        sourceScopeKey: template.sourceScopeKey,
        sourceDriveId: requiredStringField(fields, "SourceDriveId"),
        sourceItemId: requiredStringField(fields, "SourceItemId"),
        sourceLink: requiredStringField(fields, "SourceLink"),
        sourceStatus: "unavailable" as const,
        analysisRunId: analysis.runId,
        classification: stringField(fields, "Classification") ?? "unclassified",
        confidence: numericField(fields, "Confidence") ?? 0,
        reviewRequired: true,
        conflicts: [],
        provenance: {
          assertionKind: "documented-fact" as const,
          rationale:
            "This previously indexed source item was not returned by the current source-folder scan.",
        },
        details: {
          previousDetails: stringField(fields, "DetailsJson") ?? null,
          unavailableDetectedAt: new Date().toISOString(),
        },
        ...(contentHash ? { contentHash } : {}),
        rulesVersion: template.rulesVersion,
      };
    });
}

function stringField(fields: Record<string, unknown>, name: string): string | undefined {
  const value = fields[name];
  return typeof value === "string" && value.length > 0 ? value : undefined;
}

function requiredStringField(fields: Record<string, unknown>, name: string): string {
  const value = stringField(fields, name);
  if (!value) throw new Error(`Existing destination record is missing required field ${name}`);
  return value;
}

function numericField(fields: Record<string, unknown>, name: string): number | undefined {
  const value = fields[name];
  return typeof value === "number" && Number.isFinite(value) ? value : undefined;
}

function assertDestination(expected: string, actual: string): void {
  if (expected !== actual) {
    throw new Error("Destination site changed after preview; generate and approve a new plan");
  }
}

function parseSchemaOperation(value: Record<string, unknown>): SchemaOperation {
  if (value.operation === "create-list" && typeof value.listName === "string") {
    return { operation: "create-list", listName: value.listName };
  }
  if (
    value.operation === "create-column" &&
    typeof value.listName === "string" &&
    value.column &&
    typeof value.column === "object" &&
    "name" in value.column
  ) {
    return {
      operation: "create-column",
      listName: value.listName,
      ...(typeof value.listId === "string" ? { listId: value.listId } : {}),
      column: value.column as ColumnDefinition,
    };
  }
  throw new Error("Plan contains an invalid schema operation");
}
